#!/usr/bin/env python3
"""Plain-language summaries of upcoming agendas — the pipeline's one LLM step.

Phase 3 of docs/superpowers/plans/2026-08-13-github-pages-site.md. For each
upcoming/<slug>/ with an agenda-preview.md, generate summary.md (3-8
resident-friendly bullets) using the self-hosted llama-server (Qwen3.5-35B on
slayden), reached through its token-authed public endpoint. The layer is
strictly additive:

- No SLAYDEN_API_TOKEN -> print a notice and exit 0; the site falls back to
  the deterministic topic list.
- A summary is regenerated only when the preview's content hash changes
  (amended agendas), so unchanged agendas produce no diff.
- Generation failures (server down for gaming, network) warn and exit 0 so
  the Tuesday workflow still commits the deterministic preview artifacts.
- Backlog: meetings/<slug>/ folders holding an agenda-preview.md without a
  matching summary.md (the meeting passed while the LLM was down) are
  backfilled on every run, so the next run with the server up heals the gap.

Model note (measured 2026-08-18 on the Aug 13 agenda): Qwen3.5 MUST run with
thinking disabled here — thinking mode spent the entire output budget on
reasoning and produced no summary; thinking-off completed in ~8 s with an
accurate, hallucination-free bullet list.
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
from datetime import date
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
UPCOMING_DIR = REPO_ROOT / "upcoming"
MEETINGS_DIR = REPO_ROOT / "meetings"
PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "laymans-summary.md"

BASE_URL = os.environ.get("SUMMARY_BASE_URL", "https://slayden-api.duckdns.org")
MODEL = os.environ.get("SUMMARY_MODEL", "qwen3.5-35b")
TIMEOUT = 300
_HASH_RE = re.compile(r"source-sha256: ([0-9a-f]{64})")


def source_hash(preview_md: str) -> str:
    return hashlib.sha256(preview_md.encode("utf-8")).hexdigest()


def summary_is_current(summary_path: Path, preview_md: str) -> bool:
    """True if summary.md exists and was generated from this exact preview."""
    if not summary_path.exists():
        return False
    m = _HASH_RE.search(summary_path.read_text(encoding="utf-8"))
    return m is not None and m.group(1) == source_hash(preview_md)


def render_summary_md(bullets: str, preview_md: str, generated: str) -> str:
    return (f"<!-- AI-generated ({MODEL}) from agenda-preview.md on {generated}; "
            f"source-sha256: {source_hash(preview_md)} -->\n"
            "## In plain language\n\n"
            f"{bullets.strip()}\n\n"
            "*This summary was generated by an AI model from the agenda; "
            "check the agenda PDF for the authoritative wording.*\n")


def generate_bullets(preview_md: str) -> str:
    """One LLM call: agenda preview markdown -> plain-language bullet list.

    OpenAI-compatible endpoint with Qwen thinking disabled via
    chat_template_kwargs — the same recipe the aider config uses.
    """
    prompt = PROMPT_PATH.read_text(encoding="utf-8").replace("{agenda}", preview_md)
    resp = requests.post(
        f"{BASE_URL}/v1/chat/completions",
        headers={"Authorization": f"Bearer {os.environ['SLAYDEN_API_TOKEN']}"},
        json={
            "model": MODEL,
            "max_tokens": 4096,
            "messages": [{"role": "user", "content": prompt}],
            "chat_template_kwargs": {"enable_thinking": False},
        },
        timeout=TIMEOUT)
    resp.raise_for_status()
    choice = resp.json()["choices"][0]
    if choice.get("finish_reason") != "stop":
        raise RuntimeError(f"generation did not finish: {choice.get('finish_reason')}")
    text = (choice["message"].get("content") or "").strip()
    if not text.startswith(("-", "*")):
        raise RuntimeError(f"unexpected summary shape: {text[:120]!r}")
    return text


def _summarize_dir(pdir: Path, today: date, generate: "callable[[str], str]",
                   label: str) -> None:
    preview_md = (pdir / "agenda-preview.md").read_text(encoding="utf-8")
    if summary_is_current(pdir / "summary.md", preview_md):
        print(f"ok: {pdir.name}: summary.md up to date")
        return
    try:
        bullets = generate(preview_md)
        (pdir / "summary.md").write_text(
            render_summary_md(bullets, preview_md, today.isoformat()),
            encoding="utf-8")
        print(f"ok: {pdir.name}: wrote summary.md{label}")
    except Exception as exc:  # noqa: BLE001 — LLM layer must never fail the sync
        print(f"warn: {pdir.name}: summary generation failed: {exc}",
              file=sys.stderr)


def summarize(upcoming_dir: Path, meetings_dir: Path | None = None,
              today: date | None = None,
              generate: "callable[[str], str]" = generate_bullets) -> int:
    if not os.environ.get("SLAYDEN_API_TOKEN"):
        print("SLAYDEN_API_TOKEN not set; skipping plain-language summaries "
              "(the site falls back to the topic list)")
        return 0
    today = today or date.today()
    # upcoming meetings first (site main page), then the backlog of past
    # meetings whose summary was skipped while the LLM was down
    dirs: list[tuple[Path, str]] = []
    if upcoming_dir.exists():
        dirs += [(p, "") for p in sorted(upcoming_dir.iterdir()) if p.is_dir()]
    if meetings_dir is not None and meetings_dir.exists():
        dirs += [(p, " (backfilled)") for p in sorted(meetings_dir.iterdir())
                 if p.is_dir()]
    todo = [(p, label) for p, label in dirs if (p / "agenda-preview.md").exists()]
    if not todo:
        print("nothing to summarize")
        return 0
    for pdir, label in todo:
        _summarize_dir(pdir, today, generate, label)
    return 0


if __name__ == "__main__":
    sys.exit(summarize(UPCOMING_DIR, MEETINGS_DIR))
