#!/usr/bin/env python3
"""Plain-language summaries of upcoming agendas — the pipeline's one LLM step.

Phase 3 of docs/superpowers/plans/2026-08-13-github-pages-site.md. For each
upcoming/<slug>/ with an agenda-preview.md, generate summary.md via the Claude
API (3-8 resident-friendly bullets). The layer is strictly additive:

- No ANTHROPIC_API_KEY -> print a notice and exit 0; the site falls back to
  the deterministic topic list.
- A summary is regenerated only when the preview's content hash changes
  (amended agendas), so unchanged agendas produce no diff.
- Generation failures warn and exit 0 so the Tuesday workflow still commits
  the deterministic preview artifacts.
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
UPCOMING_DIR = REPO_ROOT / "upcoming"
PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "laymans-summary.md"

MODEL = "claude-opus-5"
_HASH_RE = re.compile(r"source-sha256: ([0-9a-f]{64})")


def source_hash(preview_md: str) -> str:
    return hashlib.sha256(preview_md.encode("utf-8")).hexdigest()


def summary_is_current(summary_path: Path, preview_md: str) -> bool:
    """True if summary.md exists and was generated from this exact preview."""
    if not summary_path.exists():
        return False
    m = _HASH_RE.search(summary_path.read_text(encoding="utf-8"))
    return m is not None and m.group(1) == source_hash(preview_md)


def render_summary_md(bullets: str, preview_md: str, generated: str) -> str:
    return (f"<!-- AI-generated ({MODEL}) from agenda-preview.md on {generated}; "
            f"source-sha256: {source_hash(preview_md)} -->\n"
            "## In plain language\n\n"
            f"{bullets.strip()}\n\n"
            "*This summary was generated by an AI model from the agenda; "
            "check the agenda PDF for the authoritative wording.*\n")


def generate_bullets(preview_md: str) -> str:
    """One Claude call: agenda preview markdown -> plain-language bullet list."""
    import anthropic  # imported lazily so the pipeline runs without the SDK

    client = anthropic.Anthropic()
    prompt = PROMPT_PATH.read_text(encoding="utf-8").replace("{agenda}", preview_md)
    # server-side fallback: if a safety classifier declines (implausible for a
    # public agenda, but the recommended default), retry on Anthropic's pick
    response = client.beta.messages.create(
        model=MODEL,
        max_tokens=16000,
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
        messages=[{"role": "user", "content": prompt}],
    )
    if response.stop_reason == "refusal":
        raise RuntimeError("model declined the request (stop_reason=refusal)")
    text = "".join(block.text for block in response.content if block.type == "text")
    if not text.strip().startswith("-"):
        raise RuntimeError(f"unexpected summary shape: {text[:120]!r}")
    return text


def summarize(upcoming_dir: Path, today: date | None = None,
              generate: "callable[[str], str]" = generate_bullets) -> int:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("ANTHROPIC_API_KEY not set; skipping plain-language summaries "
              "(the site falls back to the topic list)")
        return 0
    today = today or date.today()
    if not upcoming_dir.exists():
        print("no upcoming/ directory; nothing to summarize")
        return 0
    for pdir in sorted(p for p in upcoming_dir.iterdir() if p.is_dir()):
        preview_path = pdir / "agenda-preview.md"
        if not preview_path.exists():
            continue
        preview_md = preview_path.read_text(encoding="utf-8")
        if summary_is_current(pdir / "summary.md", preview_md):
            print(f"ok: {pdir.name}: summary.md up to date")
            continue
        try:
            bullets = generate(preview_md)
            (pdir / "summary.md").write_text(
                render_summary_md(bullets, preview_md, today.isoformat()),
                encoding="utf-8")
            print(f"ok: {pdir.name}: wrote summary.md")
        except Exception as exc:  # noqa: BLE001 — LLM layer must never fail the sync
            print(f"warn: {pdir.name}: summary generation failed: {exc}",
                  file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(summarize(UPCOMING_DIR))
