#!/usr/bin/env python3
"""Plain-language summaries of upcoming agendas — the pipeline's one LLM step.

Phase 3 of docs/superpowers/plans/2026-08-13-github-pages-site.md. For each
upcoming/<slug>/ with an agenda-preview.md, generate summary.md (3-8
resident-friendly bullets) using the self-hosted llama-server (Qwen3.5-35B on
slayden), reached through its token-authed public endpoint. The layer is
strictly additive:

- No SLAYDEN_API_TOKEN -> print a notice and exit 0; the site falls back to
  the deterministic topic list.
- A summary is regenerated only when the preview's content hash changes
  (amended agendas), so unchanged agendas produce no diff.
- Generation failures (server down for gaming, network) warn and exit 0 so
  the Tuesday workflow still commits the deterministic preview artifacts.
- Backlog: meetings/<slug>/ folders holding an agenda-preview.md without a
  matching summary.md (the meeting passed while the LLM was down) are
  backfilled on every run, so the next run with the server up heals the gap.

Model note (measured 2026-08-18 on the Aug 13 agenda): Qwen3.5 MUST run with
thinking disabled here — thinking mode spent the entire output budget on
reasoning and produced no summary; thinking-off completed in ~8 s with an
accurate, hallucination-free bullet list.
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
from datetime import date
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent))
import grounding  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
UPCOMING_DIR = REPO_ROOT / "upcoming"
MEETINGS_DIR = REPO_ROOT / "meetings"
PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "laymans-summary.md"

BASE_URL = os.environ.get("SUMMARY_BASE_URL", "https://slayden-api.duckdns.org")
MODEL = os.environ.get("SUMMARY_MODEL", "qwen3.5-35b")
TIMEOUT = 300

_HASH_RE = re.compile(r"source-sha256: ([0-9a-f]{64})")


def source_hash(preview_md: str) -> str:
    return hashlib.sha256(preview_md.encode("utf-8")).hexdigest()


def summary_is_current(summary_path: Path, preview_md: str) -> bool:
    """True if summary.md exists and was generated from this exact preview."""
    if not summary_path.exists():
        return False
    m = _HASH_RE.search(summary_path.read_text(encoding="utf-8"))
    return m is not None and m.group(1) == source_hash(preview_md)


def render_summary_md(bullets: str, preview_md: str, generated: str) -> str:
    return (f"<!-- AI-generated ({MODEL}) from agenda-preview.md on {generated}; "
            f"source-sha256: {source_hash(preview_md)} -->\n"
            "## In plain language\n\n"
            f"{bullets.strip()}\n\n"
            "*This summary was generated by an AI model from the agenda; "
            "check the agenda PDF for the authoritative wording.*\n")


def generate_bullets(preview_md: str) -> str:
    """One LLM call: agenda preview markdown -> plain-language bullet list.

    OpenAI-compatible endpoint with Qwen thinking disabled via
    chat_template_kwargs — the same recipe the aider config uses.
    """
    prompt = PROMPT_PATH.read_text(encoding="utf-8").replace("{agenda}", preview_md)
    resp = requests.post(
        f"{BASE_URL}/v1/chat/completions",
        headers={"Authorization": f"Bearer {os.environ['SLAYDEN_API_TOKEN']}"},
        json={
            "model": MODEL,
            "max_tokens": 8192,
            "messages": [{"role": "user", "content": prompt}],
            "chat_template_kwargs": {"enable_thinking": False},
        },
        timeout=TIMEOUT)
    resp.raise_for_status()
    choice = resp.json()["choices"][0]
    if choice.get("finish_reason") != "stop":
        raise RuntimeError(f"generation did not finish: {choice.get('finish_reason')}")
    text = (choice["message"].get("content") or "").strip()
    if not text.startswith(("-", "*")):
        raise RuntimeError(f"unexpected summary shape: {text[:120]!r}")
    return text


def _source_md(pdir: Path) -> str:
    """The LLM's full input: agenda preview + attachment excerpts when present.

    Both feed the source hash, so a late-arriving attachments file (or an
    amended agenda) triggers a richer regeneration.
    """
    source = (pdir / "agenda-preview.md").read_text(encoding="utf-8")
    att = pdir / "agenda-attachments.md"
    if att.exists():
        source += "\n\n" + att.read_text(encoding="utf-8")
    return source


def hash_input(source_md: str) -> str:
    """What the source hash covers: the prompt template plus the LLM input.

    Including the prompt means a prompt improvement regenerates the summary for
    an UPCOMING meeting, so the next agenda gets the current instructions. Past
    meetings are frozen once written - see _summarize_dir's backfill_only.
    """
    return PROMPT_PATH.read_text(encoding="utf-8") + source_md


def _generate_grounded(pdir: Path, source: str, preview: str,
                       generate: "callable[[str], str]") -> str:
    """Generate a summary, refusing to publish one that invents a dollar figure.

    Two tiers, because the failures are not equally bad.

    A fabricated dollar figure or company name is worse than no summary at all:
    the site falls back to the verbatim agenda topic list, which is honest, while
    a made-up number on a civic page is not. So those get one regeneration, and
    if the retry is also bad nothing is written and the caller logs it.

    Missing agenda items only warn. A partial summary still helps a reader, and
    the coverage check is a heuristic over word rarity - it should not be able to
    take the page down on its own.

    Kept cheap deliberately: one extra call at most, twice a week.
    """
    attempts = []
    for attempt in (1, 2):
        bullets = generate(source)
        hard = grounding.report(bullets, source)          # figures + names
        soft = grounding.uncovered_items(bullets, preview)
        attempts.append((bullets, hard, soft))
        if not hard:
            break
        print(f"warn: {pdir.name}: attempt {attempt} not grounded:", file=sys.stderr)
        for line in hard:
            print(f"  {line}", file=sys.stderr)

    bullets, hard, soft = attempts[-1]
    if hard:
        raise RuntimeError(
            f"{len(hard)} ungrounded claim(s) after {len(attempts)} attempts; "
            f"refusing to publish (site falls back to the topic list)")
    if soft:
        print(f"warn: {pdir.name}: {len(soft)} agenda item(s) not covered:",
              file=sys.stderr)
        for item_id, title in soft:
            print(f"  {item_id} {title[:80]}", file=sys.stderr)
    return bullets


def _summarize_dir(pdir: Path, today: date, generate: "callable[[str], str]",
                   label: str, backfill_only: bool = False) -> None:
    """Write summary.md for one meeting directory.

    backfill_only (past meetings): generate only when there is no summary at
    all. A past meeting's summary is a record of what was published at the
    time - a prompt change must not silently rewrite the archive, and the
    agenda it described can no longer change. Only genuine gaps get filled.

    Otherwise (upcoming meetings): regenerate whenever the hash moves, so an
    amended agenda, a late-arriving attachment, or an improved prompt is
    picked up before the meeting happens.
    """
    if backfill_only and (pdir / "summary.md").exists():
        print(f"ok: {pdir.name}: summary.md exists; past meeting, left as published")
        return
    source = _source_md(pdir)
    hashable = hash_input(source)
    if summary_is_current(pdir / "summary.md", hashable):
        print(f"ok: {pdir.name}: summary.md up to date")
        return
    preview = (pdir / "agenda-preview.md").read_text(encoding="utf-8")
    try:
        bullets = _generate_grounded(pdir, source, preview, generate)
        (pdir / "summary.md").write_text(
            render_summary_md(bullets, hashable, today.isoformat()),
            encoding="utf-8")
        print(f"ok: {pdir.name}: wrote summary.md{label}")
    except Exception as exc:  # noqa: BLE001 — LLM layer must never fail the sync
        print(f"warn: {pdir.name}: summary generation failed: {exc}",
              file=sys.stderr)


def summarize(upcoming_dir: Path, meetings_dir: Path | None = None,
              today: date | None = None,
              generate: "callable[[str], str]" = generate_bullets) -> int:
    if not os.environ.get("SLAYDEN_API_TOKEN"):
        print("SLAYDEN_API_TOKEN not set; skipping plain-language summaries "
              "(the site falls back to the topic list)")
        return 0
    today = today or date.today()
    # upcoming meetings first (site main page), then the backlog of past
    # meetings whose summary was skipped while the LLM was down
    dirs: list[tuple[Path, str, bool]] = []
    if upcoming_dir.exists():
        dirs += [(p, "", False) for p in sorted(upcoming_dir.iterdir()) if p.is_dir()]
    if meetings_dir is not None and meetings_dir.exists():
        dirs += [(p, " (backfilled)", True) for p in sorted(meetings_dir.iterdir())
                 if p.is_dir()]
    todo = [d for d in dirs if (d[0] / "agenda-preview.md").exists()]
    if not todo:
        print("nothing to summarize")
        return 0
    for pdir, label, backfill_only in todo:
        _summarize_dir(pdir, today, generate, label, backfill_only)
    return 0


if __name__ == "__main__":
    sys.exit(summarize(UPCOMING_DIR, MEETINGS_DIR))
